repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
        args: [--maxkb=2048]
    -   id: check-merge-conflict

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.2
  hooks:
  - id: ruff
    types_or: [python, pyi, jupyter]
    args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    -   id: mypy
        exclude: ^docs/
        additional_dependencies: [types-tabulate]
