name: pyintergraph
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.7
  - pip
  - graph-tool = 2.29
  - python-igraph = 0.8.0
  - mypy
  - flake8
  - pylint
  - pip:
    - networkx == 2.4
    - pytest == 5.3.5
    - pytest-cov
    - -e .