name: Run Tests

on:
  push:
    branches:
      - main
      - dev
      - use_poetry


jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          set-safe-directory: "*"
          fetch-depth: 1
      - name: install graph-tool
        run: sudo apt-get install -y python3-graph-tool
      - name: install poetry 
        uses: Gr1N/setup-poetry@v8
      - name: Create Environment
        run: |
          python3 -m venv --system-site-packages .venv
          poetry env use .venv/bin/python
          poetry install -E net
      - name: Run Tests
        run: poetry run pytest
